# Project Name
TARGET = I2C

# Sources
CPP_SOURCES = I2C.cpp

# Library Locations
LIBDAISY_DIR = $(HOME)/Desktop/DaisyExamples/libDaisy
DAISYSP_DIR = $(HOME)/Desktop/DaisyExamples/DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

