# Project Name
TARGET = axis

# Sources
CPP_SOURCES = axis.cpp BNO055.cpp

# Library Locations
LIBDAISY_DIR = $(HOME)/Desktop/DaisyExamples/libDaisy
DAISYSP_DIR = $(HOME)/Desktop/DaisyExamples/DaisySP


# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

